### ISSUE TITLE
postgres problem

### ISSUE THREAD

**Issue by KamaR0308** [savareyhano/Sistem-Informasi-Inventaris-Barang#14]
Hello. I'm having problems starting the database in this project. Can I contact you?

**Comment by savareyhano** [comment]
> Hello. I'm having problems starting the database in this project. Can I contact you?

You can describe your problem here

**Comment by KamaR0308** [comment]
When I try to run the command
`npm run setup-db`
An error occurs

![problem](https://github.com/savareyhano/Sistem-Informasi-Inventaris-Barang/assets/105632738/45778ed2-1446-4681-bea2-1e667cc3a7f5)

In this case, a database is created in postgres

**Comment by savareyhano** [comment]
- Can i know what is your operating system are?
This command i use is for windows, i haven't tested it in other operating systems.
- Have you already checked that the postgres tools is already registered on your PATH?
- If all question above is good, can you confirm does the setup-db.js is successfully created the database but not the restore?
If this is the case you can import the "db.sql' manually using cli or pgadmin

**Comment by KamaR0308** [comment]
1. Windows 
2. > Have you already checked that the postgres tools is already registered on your PATH? Are you talking about whether postgres is installed on my computer?
3. > If all question above is good, can you confirm does the setup-db.js is successfully created the database but not the restore?
How can I do it? I tell it like it is. After I run the command
npm run setup-db
this error appears, but the database is created


> The error message is not quite clear to me, looks like it's using another language than english (?) 
Yes, it uses another language besides English

**Comment by KamaR0308** [comment]
[sql.txt](https://github.com/savareyhano/Sistem-Informasi-Inventaris-Barang/files/14160735/sql.txt)
could this be the problem?

**Comment by KamaR0308** [comment]
![image](https://github.com/savareyhano/Sistem-Informasi-Inventaris-Barang/assets/105632738/d9d39704-7b87-4438-90e4-27890b80ab43)
if you look inside, there are also hieroglyphs

**Comment by KamaR0308** [comment]
2. > Have you already checked that the postgres tools is already registered on your PATH? 

ok, looks like that was the problem

**Comment by savareyhano** [comment]
> 1. Windows
> 2. > If all question above is good, can you confirm does the setup-db.js is successfully created the database but not the restore?
>    > How can I do it? I tell it like it is. After I run the command
>    > npm run setup-db
>    > this error appears, but the database is created
> 
> > The error message is not quite clear to me, looks like it's using another language than english (?)
> > Yes, it uses another language besides English

Ok, you can try to import the db.sql manually into the postgres using pgadmin if the problem is still persist.
