### ISSUE TITLE
Error Gan

### ISSUE THREAD

**Issue by GodenID** [savareyhano/Sistem-Informasi-Inventaris-Barang#6]
kenapa ya pas di npm install malah error
<img width="960" alt="Screenshot_1" src="https://github.com/savareyhano/Sistem-Informasi-Inventaris-Barang/assets/62768667/9af801c6-ecd1-4991-af18-33e517958025">
<img width="960" alt="Screenshot_2" src="https://github.com/savareyhano/Sistem-Informasi-Inventaris-Barang/assets/62768667/636d3896-cda5-48c3-8b5b-5e24c78b571a">

**Comment by savareyhano** [comment]
Tidak ada masalah:
![Screenshot 2023-12-15 072631](https://github.com/savareyhano/Sistem-Informasi-Inventaris-Barang/assets/32730327/271060e9-6fe4-4ac4-bcc8-7769a323c0fc)

Sepertinya masalahnya ada pada Visual Studio, atau Node.js/npm kamu. Coba lakukan update keduanya, atau coba hapus instalasi keduanya kemudian lakukan instalasi baru.

Referensi yang mungkin bermanfaat:

- [node-gyp error Could not find any Visual Studio installation to use](https://stackoverflow.com/questions/70315519/node-gyp-error-could-not-find-any-visual-studio-installation-to-use)
- [Could not find any Visual Studio installation to use after trying all the tips I could find online](https://github.com/nodejs/node-gyp/issues/2203)

**Comment by GodenID** [comment]
lah iya ya aneh banget, pake nodejs sama vscode yang update paling baru kan ya gan?
